modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/svennieke/trashed/issues"

[[mods]]
modId="trashed"
version="${file.jarVersion}"
displayName="Trashed"
displayURL="https://minecraft.curseforge.com/projects/trashed"
logoFile="logo.png"
authors="svennieke, Mrbysco"
description='''
Adding Trash Can's to Minecraft.
'''

[[dependencies.statues]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.statues]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"