modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/mrbysco/trashed/issues"
license="MIT"

[[mods]]
modId="trashed"
version="${file.jarVersion}"
displayName="Trashed"
displayURL="https://minecraft.curseforge.com/projects/trashed"
logoFile="logo.png"
authors="ShyNieke, Mrbysco"
description='''
Adding Trash Can's to Minecraft.
'''
[[dependencies.trashed]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.trashed]]
modId="neoforge"
mandatory=true
versionRange="[20.2.64-beta,)"
ordering="NONE"
side="BOTH"