modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/mrbysco/trashed/issues"
license="MIT"

[[mods]]
modId="trashed"
version="${file.jarVersion}"
displayName="Trashed"
displayURL="https://minecraft.curseforge.com/projects/trashed"
logoFile="logo.png"
authors="ShyNieke, Mrbysco"
description='''
Adding Trash Can's to Minecraft.
'''
[[dependencies.trashed]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,1.20)"
ordering="NONE"
side="BOTH"