modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/mrbysco/trashed/issues"
license="MIT"

[[mods]]
modId="trashed"
version="${file.jarVersion}"
displayName="Trashed"
displayURL="https://minecraft.curseforge.com/projects/trashed"
logoFile="logo.png"
authors="ShyNieke, Mrbysco"
description='''
Adding Trash Can's to Minecraft.
'''
[[dependencies.trashed]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.trashed]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"