modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/mrbysco/trashed/issues"
license="MIT"

[[mods]]
modId="trashed"
version="${file.jarVersion}"
displayName="Trashed"
displayURL="https://minecraft.curseforge.com/projects/trashed"
logoFile="logo.png"
authors="ShyNieke, Mrbysco"
description='''
Adding Trash Can's to Minecraft.
'''
[[dependencies.trashed]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.10,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.trashed]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.10.0-beta,)"
ordering="NONE"
side="BOTH"